INSERT INTO `courses` (`code`, `title`, `units`, `description`) VALUES
('COMP1100', 'Programming as Problem Solving', 6, 'Functional programming in Haskell as a way to think about problems.'),
('COMP1110', 'Structured Programming', 6, 'Object-oriented programming, data structures and testing in Java.'),
('COMP1600', 'Foundations of Computing', 6, 'Logic, proof, automata and the mathematics behind programs.'),
('COMP2100', 'Software Design Methodologies', 6, 'Designing larger programs: patterns, abstraction and structure.'),
('COMP2120', 'Software Engineering', 6, 'Working as a team on a real software project.'),
('COMP2300', 'Computer Organisation and Program Execution', 6, 'How programs run on hardware, from assembly up.'),
('COMP2310', 'Systems, Networks and Concurrency', 6, 'Concurrent programs, operating systems and networks.'),
('COMP2400', 'Relational Databases', 6, 'Relational modelling, SQL and database design.'),
('COMP2420', 'Introduction to Data Management, Analysis and Security', 6, 'Working with data end to end, safely.'),
('COMP3310', 'Computer Networks', 6, 'Protocols and the design of the internet.'),
('COMP3425', 'Data Mining', 6, 'Finding patterns in large datasets.'),
('COMP3600', 'Algorithms', 6, 'Designing and analysing efficient algorithms.'),
('COMP3620', 'Artificial Intelligence', 6, 'Search, reasoning and planning for intelligent agents.'),
('COMP3670', 'Introduction to Machine Learning', 6, 'The mathematics and practice of learning from data.'),
('COMP3900', 'Human-Computer Interaction', 6, 'Designing and evaluating interfaces with people.'),
('COMP4020', 'Agentic Coding Studio', 6, 'Building software by directing coding agents, crit by crit.'),
('COMP4300', 'Parallel Systems', 6, 'Programming many processors at once.'),
('MATH1013', 'Mathematics and Applications 1', 6, 'Calculus and linear algebra for science and engineering.'),
('MATH1014', 'Mathematics and Applications 2', 6, 'Further calculus and linear algebra.'),
('STAT1003', 'Statistical Techniques', 6, 'Introductory statistics for analysing data.');
